### ISSUE TITLE
Clarify ngrok vs. shopify-app-cli authtoken config script creation differences or lack thereof.

### ISSUE THREAD

**Issue by keithrbennett** [Shopify/shopify-app-cli#1009]
# Summary

Explicitly state the differences, or lack of differences, between the two methods (ngrok and shopify) of saving the ngrok auth token to `~/.ngrok2/ngrok.yml`.

# Description

Both the ngrok web site (https://dashboard.ngrok.com/get-started/setup) and the `shopify serve` output (see below) specify scripts for saving the auth token to `~/.ngrok2/ngrok.yml`. The commands are `ngrok authtoken <token>` and `shopify tunnel auth <token>`, respectively.

```
⭑ To avoid tunnels that timeout, it is recommended to signup for a free ngrok
account at https://ngrok.com/signup. After you signup, install your
personalized authorization token using shopify tunnel auth <token>.
```

If the `shopify tunnel auth` command does anything _in addition to_ what `ngrok authtoken` does, then it would be helpful to state so in the output.

Otherwise, if writing to that config file is _all_ it does, I recommend removing the `shopify tunnel auth` command, and instead specifying ngrok's command in the output.

**Comment by paulomarg** [comment]
Hi @keithrbennett, the `auth` command is essentially an alias of `ngrok authtoken`, with the addition of ensuring ngrok is installed on the computer.

Running either of the commands will have the same effect and the tunnel will work the same way regardless of how the auth token is set up. That command is there to remove the burden on the developer to discover and run the `authtoken` command on ngrok - since the Shopify CLI auto-installs ngrok and supplies other `tunnel` commands such as `start` / `stop`, it is easier for the user if they can perform all ngrok-related actions via the CLI (even though they don't *have* to).

**Comment by keithrbennett** [comment]
I've submitted a PR (#1011) to add a little explanatory text to the `tunnel` documentation.

**Comment by keithrbennett** [comment]
@paulomarg Thank you for that clarification. That's exactly the kind of information that would have been very helpful for me to read. I'm thinking maybe I should modify the PR to include some of it.

**Comment by keithrbennett** [comment]
I've just added a couple of phrases to the original PR, I think that will be enough.

**Comment by paulomarg** [comment]
Thank you for your contribution @keithrbennett, we'll evaluate the PR and merge it!

**Comment by thecodepixi** [comment]
Thanks for contributing, @keithrbennett! I noted this on your PR, but we recently moved the CLI docs over to Shopify.dev. Closing this issue since the docs no longer live on GitHub.
