### ISSUE TITLE
Cli generated Node app, Shopify Dashboard render order issues.

### ISSUE THREAD

**Issue by Sheldonfrith** [Shopify/shopify-app-cli#1090]
# Issue summary

This occurs with the default/fresh NODE app generated by the shopify-app-cli...

Essentially my app renders fullscreen before any part of the shopify admin UI renders, then there is a flicker, then the shopify admin UI renders with my app inside it as expected. Wanting to get rid of this initial fullscreen render.

## Expected behavior

The shopify shop's Admin UI should render first, then my app should render inside of its container.

## Actual behavior

My app renders first (fullscreen), then there is a brief screen flicker, then the shopify Admin UI loads, with my app in the proper position now.

## Steps to reproduce the problem

1. Create a new Node app using the shopify-app-cli
2. Go to your development store's "Apps" tab, click on the newly created app (or install it if you haven't already)
3. Watch as the shopify UI dissappears, the vanilla app appears fullscreen (with the url changing to be just the url of the app), etc.

- App type: Node, public
- Operating System: Windows 10
- Shell: Git Bash
- Ruby version (ruby -v):

**Comment by Sheldonfrith** [comment]
More details on the problem: It seems to happen when the app is opened for the first time after install, or opened for the first time after URL change only.

**Comment by paulomarg** [comment]
Hi @Sheldonfrith! What you are seeing there is the app performing OAuth, which unfortunately must always be done from the top level of a page for security reasons, i.e. it can't be done while the app is still embedded in Admin.

If the merchant needs to perform OAuth, the app will:
1. Take them to the top level (by loading the app directly and not within the Admin)
1. Redirect them to Shopify to authorize the app
1. Redirect them to the Admin with the embedded app after authorization

That is where the flicker you see comes from. We can't work around that restriction, but that only happens when OAuth is necessary.

**Comment by Sheldonfrith** [comment]
Thank you for the explanation!
