### ISSUE TITLE
Updating app scopes

### ISSUE THREAD

**Issue by DiegoNakatori** [Shopify/shopify-app-cli#1137]
I need to update the app scope for my react/node shopify app, but for the life of me I can not figure out how. The documentation is unclear to me: https://shopify.dev/tutorials/authenticate-with-oauth . How do I go about prompting a fresh authorization without removing the app? Is there something I am missing with regards to the CLI? I am redirecting the user with the following command:

```javascript
// Redirect to app with shop parameter upon auth
        ctx.redirect(
          `https://${shop}/admin/oauth/authorize?client_id=${SHOPIFY_API_KEY}&scope=${SCOPES}&redirect_uri=${redirect}&state=${nonce}&grant_options[]=offline`
        );

**Comment by paulomarg** [comment]
Whenever a user goes through the Shopify OAuth process, we check the scopes to see if they need to be updated - so if the app's scopes have changed since the last OAuth, Shopify will prompt the user to authorize the new scopes.

The redirection you posted should be enough to trigger the update when needed. It's worth pointing out that if your app already has the `write_<scope>` scope to something and you add `read_<scope>` Shopify will not trigger the update because `write` scopes already contain `read` scopes.

Hope this helps!

**Comment by DiegoNakatori** [comment]
Thank you for your response, however, the redirect I posted returns a page saying that my request origin could not be verified. What am I doing wrong? Has it something to do with the nonce maybe?

**Comment by paulomarg** [comment]
The URL seems good to me, Shopify doesn't really do anything with the `nonce`, it's there so the app can check it to make sure it fired the request when it comes back.

Is your app embedded within the Shopify Admin when you call `ctx.redirect`? If that's the case, you'll want to use the [App Bridge Redirect](https://shopify.dev/tools/app-bridge/actions/navigation/redirect) action to send the user outside of the Admin, otherwise OAuth can't be done.

**Comment by DiegoNakatori** [comment]
Thanks for your help, it appears that the scope has been added. However, I did not see a screen where I had to reconfirm the scopes.

**Comment by scole954387** [comment]
> Thanks for your help, it appears that the scope has been added. However, I did not see a screen where I had to reconfirm the scopes.

I'm a newb but had this recently.  Restart your server.  Then go to the store admin with the app installed and try to access the app. It should say that the app needs to be updated.  This is where the app is installing again with the updated scopes.

That's what happened with mine when I updated the scopes.

**Comment by paulomarg** [comment]
Fair point @scole954387! Changes to the `.env` file are only picked up when the server is restarted.

**Comment by mkevinosullivan** [comment]
Closing this as it's not a CLI issue
