### ISSUE TITLE
Shopify app reloads frequently with enable cookie error and I get "Expected a valid shop query parameter" in my page body while switching between pages.

### ISSUE THREAD

**Issue by AkhilKamath** [Shopify/shopify-app-cli#1164]
# Issue summary

Hi,

I am new to app development on Shopify. However I am facing a blocker while developing my app. My app is a simple app with a couple of pages and nothing else! Followed shopify's tutorial to add pages. But when I am switching between the pages I get this in my page body instead of the actual content - ```Expected a valid shop query parameter```

Also I get this pop up while interacting with app and the entire app reloads. This pop up asks me to enable cookies but my browser is already set to accept cookies form all sites.

```Enable cookies

You must manually enable cookies in this browser in order to use this app within Shopify.

Cookies let the app authenticate you by temporarily storing your preferences and personal information. 
They expire after 30 days
```

## Specifications

- App type: Node + React
- Operating System: Ubuntu 20.04.2 LTS
- Ruby version (ruby -v): 2.7.0p0
- Browser -  Chrome - Version 89.0.4389.114 (Official Build) (64-bit)

**Comment by paulomarg** [comment]
Hey @AkhilKamath, I think you may be running into some problems that are being discussed in other issues. I'm going to close this one so we can track things in a single location:

For the issues with navigating across different pages, this is usually because your React app is missing the `ClientRouter`: https://github.com/Shopify/koa-shopify-auth/issues/76#issuecomment-805844570
For the cookie page issue showing up: https://github.com/Shopify/shopify-app-node/issues/616
