### ISSUE TITLE
Add support for starting a tunnel from ArgoServe

### ISSUE THREAD

**Issue by t6d** [Shopify/shopify-app-cli#1174]
The Shopify CLI already provides a wrapper for starting a ngrok tunnel in a separate process using 

```ruby
ShopifyCli::Tunnel.start(context, port: port)
```

The return value of this method is the URL the tunnel is running on, which needs to be forwarded to the node server. Starting the tunnel should be optional and controlled by a boolean property passed to `ArgoServe`. 

In summary, the following tasks need to be accomplished

- [ ] Integrate `ShopifyCli::Tunnel` into ~`ArgoServe`~ `Extension::Commands::Serve` https://github.com/Shopify/shopify-app-cli/pull/1191
- [ ] Always pass port to serve command as an argument https://github.com/Shopify/shopify-app-cli/pull/1191
- [ ] Remove hard coded port in argo-admin-template https://github.com/Shopify/argo-admin-template/pull/96
- [ ] Remove hard coded port in argo-checkout-template https://github.com/Shopify/argo-checkout-template/pull/47

**Comment by cecyc** [comment]
@t6d Some follow-up questions:

Assuming default port is `39351` for this. We discussed checking to see if the port is available.

What is the desired flow if the port is unavailable?

* Close it? (I assume we don't want to close it since that would be an unintended consequence of the command)
* Pick a new random port?
  * If picking a random port, what would the criteria be? Just any random port, or use something like `39352` (and so forth if that is unavailable)?
 
Or do we want to provide the ability for someone to determine the port by passing in a `--port` flag? 
i.e. `shopify serve --tunnel=true --port=123456` ?

Thanks!
