### ISSUE TITLE
ngrok default host as a parameter

### ISSUE THREAD

**Issue by Jtosbornex** [Shopify/shopify-app-cli#249]
# Issue summary

ngrok default host as a parameter

## Expected behavior

I should be able to use the HOST environment variable to set the default ngrok host url

## Actual behavior

HOST environment variable is not actually used in development.

## Steps to reproduce the problem

0. set up a dedicated tunnel in ngrok.
1. setup an app using the CLI
2. set the HOST variable in the .env file.
3. Go to the url in the HOST variable in the .env file
4. You will get default ngrok text instead of the expected callback text.

## Specifications

- Operating System: Mac OSX  Mojave 10.14.15 
- Shell: ITerm Build 3.2.9
- Ruby version (ruby -v): ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]

**Comment by katiedavis** [comment]
Hi @Jtosbornex, I think you're asking to be able to set the ngrok tunnel to a specific host, right?
Ie: ngrok http 5000 or whichever host you choose?

There's a lot of configurations for ngrok so I'm not sure what kind of enhancement we will be making, but I have created an issue to ask before we set the tunnel so that you could just run your own tunnel set to whatever you please: https://github.com/Shopify/shopify-app-cli/issues/250
