### ISSUE TITLE
Delete project folder if `create` fails

### ISSUE THREAD

**Issue by ErinRenNumber1** [Shopify/shopify-app-cli#586]
# Issue summary
This is a proposal for removing the project folder when `create` command fails.  The problem described in the linked [issue](https://github.com/Shopify/script-service/issues/1190) happened for a Script project, but could happen with any project.

**Comment by tanema** [comment]
Hi Erin, in the linked issue you said that you do not create the folders but your project-creator does this https://github.com/Shopify/shopify-app-cli/blob/master/lib/project_types/script/script_project.rb#L24-L29 

The CLI does not handle creating folders or maintaining which folders you use for your project because they could be created through a command something like `git clone` or `rails new` so this will something that your project-type will need to handle

**Comment by ErinRenNumber1** [comment]
@tanema Yes, you are right.  Scripts project needs to add the logic to clean up here.  However, I hope this is consistent with other projects too.  For example, if `git` fails here: https://github.com/Shopify/shopify-app-cli/blob/b64e3c362eca01f45858f4227f545c8c200cf4d8/lib/shopify-cli/git.rb#L134, or anywhere else in initializing, for example, https://github.com/Shopify/shopify-app-cli/blob/b64e3c362eca01f45858f4227f545c8c200cf4d8/lib/project_types/node/commands/create.rb#L109, do you know if that app project is deleted?

**Comment by tanema** [comment]
If the git command fails then git does not create the folder. This is handled by Git.

**Comment by ErinRenNumber1** [comment]
Thank you.  Will close it now!!
