### ISSUE TITLE
Env file should have shop as a required property for script projects

### ISSUE THREAD

**Issue by erik-shopify** [Shopify/shopify-app-cli#745]
# Issue summary

Currently, the .env file has `api_key` and `api_secret_key` as required properties. At least in the case of a script project, `shop` should also be a required property.

**Comment by tanema** [comment]
A PR was just merged to add a task to ensure that a shop is present. We don't require a shop while creating the env because there are lots of new partners that are starting out and do not have a development shop yet and the minimum requirements to start getting an app running is the API key and secret. We then point the user to the dashboard to create a shop. I am not sure we will implement this so you will either need to make this a validation in your code or use our task to ensure that shop has been selected.

**Comment by ErinRenNumber1** [comment]
Right, it looks like we can just use `ensure_dev_store`.  👍   Thanks!!

**Comment by erik-shopify** [comment]
Actually `ensure_dev_store` isn't what we need, as it only verifies if a specified `SHOP_DOMAIN` in the `.env` file is a valid domain owned by the org.  But, we want to be able to prompt for the dev_shop if one isn't in the `.env` file.  We looked at `SelectOrgAndShop` task, but it's always prompting and doesn't look at the `.env` file.  So, I will reopen this ticket for now.

**Comment by tanema** [comment]
What you are describing seems like a different issue so please open a new issue with the problem described and changes you would like to see in the task
