### ISSUE TITLE
I'm always getting: ngrok tunnel has timed out

### ISSUE THREAD

**Issue by FDiskas** [Shopify/shopify-app-cli#888]
I'm always getting 
```
ngrok tunnel has timed out, restarting...
ngrok tunnel could not be stopped. Try running killall -9 ngrok
```
```
shopify cli v1.2.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
OS: Darwin x64 19.6.0
```

_Originally posted by @FDiskas in https://github.com/Shopify/shopify-app-cli/pull/776#issuecomment-700152719_

**Comment by tanema** [comment]
When you say *always* what do you mean. How often?

**Comment by paulomarg** [comment]
This could be a similar situation to https://github.com/Shopify/shopify-app-cli/issues/892 - if you started your tunnel with `sudo shopify tunnel` and it expired, you will get that error message if you try to run `shopify tunnel start` since it won't be able to kill the current process.

You could check if ngrok is running under root (`ps aux | grep ngrok`) and run `sudo shopify tunnel stop` to stop it if that's the case.

**Comment by FDiskas** [comment]
I did not started with sudo and ngrox process was not found. :/

**Comment by paulomarg** [comment]
Hi @FDiskas, we've recently fixed an issue where this could happen for partners who:
- Are using an ngrok account
- Have accents in their ngrok account names

If that might be your case, you could try updating your CLI to version 1.3.1 which has that fix.

**Comment by FDiskas** [comment]
sorry abandoned that project. Can't specify more details

**Comment by gokaka** [comment]
@FDiskas @paulomarg 


## Same issue here:
```
❯ shopify serve
✗ ngrok tunnel has timed out, restarting ...
✗ ngrok tunnel could not be stopped. Try running killall -9 ngrok
```

The problem seems like shopify-cli failed find the PID file, then it failed to stop the ngrok

## My solution:

- found my Shopify CLI (v1.0.4) was installed in path `/usr/local/Cellar/shopify-cli/1.0.4/`

in your case, the path should be like `/usr/local/Cellar/shopify-cli/1.2.0/`


- comment out the `ShopifyCli::ProcessSupervision.stop(:ngrok)` process in file
`/usr/local/Cellar/shopify-cli/1.0.4/src/lib/shopify-cli/tunnel.rb`
 (https://github.com/Shopify/shopify-app-cli/blob/master/lib/shopify-cli/tunnel.rb#L169-L171)

```
    def restart_ngrok(ctx, port)
#      unless ShopifyCli::ProcessSupervision.stop(:ngrok)
#        ctx.abort(ctx.message('core.tunnel.error.stop'))
#      end
      start_ngrok(ctx, port)
    end
```

- Then rerun `shopify serve`, now it will skip the stop ngrok, everything look good.

```
❯ shopify serve
✗ ngrok tunnel has timed out, restarting ...
✓ ngrok tunnel running at https://6016cf0f5ea2.ngrok.io
...
```

- _**You'd better reverse the `tunnel.rb` changes at last.**_

**Comment by Bytesu** [comment]
> This could be a similar situation to #892 - if you started your tunnel with `sudo shopify tunnel` and it expired, you will get that error message if you try to run `shopify tunnel start` since it won't be able to kill the current process.
> 
> You could check if ngrok is running under root (`ps aux | grep ngrok`) and run `sudo shopify tunnel stop` to stop it if that's the case.

it does not work. I run `sudo shopify node tunnel stop` , it says `ngrok tunnel not running` , and I run `shopify node tunnel start`, it says `ngrok tunnel has timed out, restarting…, ngrok tunnel could not be stopped. Try running killall -9 ngrok`. but nothing about ngrok

**Comment by pixelcure** [comment]
i'm also getting the same issue. running shopify cli vs `2.7.0`
![Screen Shot 2021-11-16 at 1 48 07 PM](https://user-images.githubusercontent.com/1720037/142046952-1da25fbd-3f55-4ed1-a980-2873690e431d.png)

**Comment by PranayKakati26** [comment]
> > > > This could be a similar situation to #892 - if you started your tunnel with `sudo shopify tunnel` and it expired, you will get that error message if you try to run `shopify tunnel start` since it won't be able to kill the current process.
> > > > You could check if ngrok is running under root (`ps aux | grep ngrok`) and run `sudo shopify tunnel stop` to stop it if that's the case.
> > > 
> > > 
> > > it does not work. I run `sudo shopify node tunnel stop` , it says `ngrok tunnel not running` , and I run `shopify node tunnel start`, it says `ngrok tunnel has timed out, restarting…, ngrok tunnel could not be stopped. Try running killall -9 ngrok`. but nothing about ngrok
> > 
> > 
> > Same
> 
> having the same issue, running shopify cli vs `2.7.0`, screenshot below to see initial serving of node app failing ![Screen Shot 2021-11-16 at 1 48 07 PM](https://user-images.githubusercontent.com/1720037/142047104-ebce4599-7959-4e04-943e-7d3c4c41c3d0.png)

Create an Ngrok account , When you login to your ngrok account they will give you an auth token
Copy that authtoken... Go to your terminal , open your app and run 
sudo shopify app tunnel auth [auth token you get from ngrok ]
